
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 31 00:51:28 CET 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 38;
  public static final int LBRACKET = 11;
  public static final int CHAR = 44;
  public static final int CONST = 5;
  public static final int EQUALS = 30;
  public static final int LPAREN = 14;
  public static final int SEMI = 6;
  public static final int CONTINUE = 20;
  public static final int LESS = 34;
  public static final int FOR = 18;
  public static final int MINUS = 28;
  public static final int RPAREN = 15;
  public static final int AND = 27;
  public static final int MOREEQUAL = 33;
  public static final int LESSEQUAL = 35;
  public static final int OR = 26;
  public static final int BOOL = 43;
  public static final int COMMA = 7;
  public static final int CLASS = 9;
  public static final int INC = 24;
  public static final int DIFFERENT = 31;
  public static final int MULTIPLY = 37;
  public static final int PLUS = 36;
  public static final int IF = 16;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int RETURN = 21;
  public static final int RBRACKET = 12;
  public static final int EQUAL = 8;
  public static final int NEW = 29;
  public static final int error = 1;
  public static final int NUMBER = 41;
  public static final int MOD = 39;
  public static final int IDENT = 42;
  public static final int BREAK = 19;
  public static final int VOID = 13;
  public static final int LBRACE = 3;
  public static final int ELSE = 17;
  public static final int ENUM = 10;
  public static final int READ = 22;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int DEC = 25;
  public static final int PRINT = 23;
  public static final int MORE = 32;
}

